// Generated by CoffeeScript 1.4.0

Workspace.controller('ProjectCtrl', [
  '$scope', '$stateParams', 'annotationService', function($scope, $stateParams, annotationService) {
    $scope.currentProject = _.find(annotationService.mockData, function(item) {
      return item.project.id === $stateParams.projectID;
    });
    return em.unit;
  }
]);
