// Generated by CoffeeScript 1.4.0

Workspace.controller('ProjectCtrl', [
  '$scope', '$stateParams', 'collaborationService', function($scope, $stateParams, collaborationService) {
    $scope.currentProject = _.find(collaborationService.mockData, function(item) {
      return item.project.id === $stateParams.projectID;
    });
    return em.unit;
  }
]);
